language: julia

sudo: false

os:
  - linux
  - osx
  - windows

julia:
  - 0.6
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'cd(Pkg.dir("Base58")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
